(define (area_circle r)
(sqrt (* 3.14 (* r r)))
)

(display "Area of a circle with a radius of 2: ")
(display (area_circle 2))
(newline)
(display "Area of a circle with a radius of 5: ")
(display (area_circle 5))
(newline)
(display "Area of a circle with a radius of 8: ")
(display (area_circle 8))
(newline)

(exit)
